### ISSUE TITLE
compiling mdaJX10 to a .dll

### ISSUE THREAD

**Issue by Wildersnuth** [moddevices/mda-lv2#8]
Hey might someone help me I try to compile one of ur effects zo a dll and use it as a vst. so i got this repository and the steinbergs sdk 2.4, i also got the lv2 dependencies, started a project and load everything in it. but i still got a lot of the "identifier is not defiend" errors so it feels like i am stil missing something. Thank in advance!

**Comment by falkTX** [comment]
you are in the wrong place. this is specifically for the mda **LV2** fork, of another existing mda port.
the vst sdk is not used or needed, and this repo does not generate vst plugins.

for generating windows lv2 plugins, get a compiler, python and run the usual waf stuff to configure and build the project.
but due to windows not having the tools needed to do this from the get-go, it becomes hard to do it there.
look into msys2 for something that does parts of this on windows.
